# Generated by Django 4.1.7 on 2023-03-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=150)),
                ('nivel', models.CharField(max_length=1)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('n_registro_cnh', models.CharField(blank=True, max_length=11, null=True)),
                ('cdi', models.CharField(blank=True, max_length=12, null=True)),
                ('assinatura_digital', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
