# Generated by Django 4.1.7 on 2023-03-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=150)),
                ('expediente', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'contato',
            },
        ),
    ]
