# Generated by Django 4.1.7 on 2023-03-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
