# Generated by Django 4.1.7 on 2023-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_1', models.CharField(max_length=150)),
                ('pergunta_2', models.CharField(max_length=150)),
                ('pergunta_3', models.CharField(max_length=150)),
                ('pergunta_4', models.CharField(max_length=150)),
                ('pergunta_5', models.CharField(max_length=150)),
                ('pergunta_6', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'perguntas',
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_1', models.CharField(max_length=150)),
                ('resposta_2', models.CharField(max_length=150)),
                ('resposta_3', models.CharField(max_length=150)),
                ('resposta_4', models.CharField(max_length=150)),
                ('resposta_5', models.CharField(max_length=150)),
                ('resposta_6', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'respostas',
            },
        ),
    ]
